lazy loading and width+height for <img>
oklabflensburg/oddfl pull request #2
Opened 2024-02-15 02:40 UTC by midzer

Hi,

been a pleasure to work on this :)

* reorder <head>, check https://github.com/rviscomi/capo.js for reference
* preload hero font
* slightly larger `odd-logo.svg`
* `loading="lazy"` for all below the fold images
* set width+height for all images to reduce Layout Shift
* slightly larger Partner images
* moved own logo to bottom ("the donkey calls itself at the end")

Further possible optimizations regarding page payload:

* reduce .svg size with https://jakearchibald.github.io/svgomg/ (our own logo would save 50%)
* hero background to .svg (perhaps original file was a .svg anyway?)

Cya on monday,
midzer

2024-02-15 09:36 UTC, p3t3r67x0 commented on src/index.html
> +    <link rel="shortcut icon" type="image/x-icon" href="./static/favicon.ico">
passt

2024-02-15 09:36 UTC, p3t3r67x0 commented on src/index.html
> +    <link rel="stylesheet" href="./main.css">
passt

2024-02-15 09:36 UTC, p3t3r67x0 commented on src/index.html
> +    <link rel="preload" href="./static/fonts/grotesk/HKGrotesk-Bold.woff2" as="font" type="font/woff2" crossorigin>
passt

2024-02-15 09:52 UTC, p3t3r67x0 requested changes
@midzer thank you for your pull request. Would you mind, unfortunately we couldn't approve your PR directly due to some minor issues. Images with a fixed width and height does not look correct in the viewports XS, SM, MD, LG and XL. These images does not retain the desired optical shape in all viewports in all tested devices. Further more, we cannot change logo width and height in the partner section, because any changes must be discussed in advance with the partners and the arrangement of the logos in the respective viewports. The arrangement in the respective viewports have already been approved. The idea preloading fonts is pretty great. The order of the `<head>` makes sense and looks good. Using attribute `loading="lazy"` is pretty straight forward. Best regards

2024-02-15 09:52 UTC, p3t3r67x0 commented on src/index.html
> +
Thx, for your suggestion, we must discuss design changes first with @roaldchristesen and @chanty1512

2024-02-15 09:52 UTC, p3t3r67x0 commented on src/index.html
> -            <p class="text-lg lg:text-2xl leading-7 mb-5 lg:mb-8">Ein Event vom OK Lab Flensburg. Mit freundlicher Unterstützung von unseren Partnern und Förderern</p>
Thx. @roaldchristesen would you be so kind and have a look? As far as I know the wording is the same as on our print layouts. Could you be so kind and join this discussion?

2024-02-17 19:32 UTC, roaldchristesen commented on src/index.html
> -            <p class="text-lg lg:text-2xl leading-7 mb-5 lg:mb-8">Ein Event vom OK Lab Flensburg. Mit freundlicher Unterstützung von unseren Partnern und Förderern</p>
@midzer Danke für deine Optimierungsvorschläge!
Da wir in allen unseren anderen Materialien den Satz "Ein Event vom OK Lab Flensburg. Mit freundlicher Unterstützung von unseren Partnern und Förderern" verwenden, würde ich ihn für dieses Jahr gerne so belassen.
Ebenfalls das Logo oben. So kurz vor dem Event möchten wir aus Kapizitätsgründen keine Designänderungen vornehmen.

2024-02-17 21:30 UTC, midzer commented on src/index.html
> -            <p class="text-lg lg:text-2xl leading-7 mb-5 lg:mb-8">Ein Event vom OK Lab Flensburg. Mit freundlicher Unterstützung von unseren Partnern und Förderern</p>
Okay, ich reverte genannte Änderungen später.

2024-02-18 09:28 UTC, p3t3r67x0 approved these changes
@midzer vielen dank für dein tollen Input. :rocket:

2024-02-18 09:28 UTC, merged